# Uncomment the next line to define a global platform for your project
platform :ios, '11'

target 'Constructify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Constructify
  pod 'SwiftyJSON'
  pod 'IQKeyboardManager'
  pod 'M13ProgressSuite'
  pod 'Kingfisher', '~> 4.0'
  pod 'Alamofire', '~> 5.0.0-rc.2'

  target 'ConstructifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConstructifyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
